name: "RUN TESTS ON PUSH then deploy"
on:
  push:
    branches:
      - main
jobs:
    test_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up npm
              uses: actions/setup-node@v1
              with:
                node-version: '18.x'
            - name: Install dependencies
              run: npm install
            - name: Set up AWS CLI
              run: |
                echo "[default]" >> ~/.aws/config
                echo "region = us-east-1" >> ~/.aws/config
                echo "[default]" >> ~/.aws/credentials
                echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
                echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
                aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws configure set default.region us-east-1
      
            - name: Get secret from AWS Secrets Manager
              id: get_secret
              run: |
                SECRET_VALUE=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:us-east-1:123456789012:secret:my-secret --query SecretString --output text)
                echo "::set-output name=secret_value::$SECRET_VALUE"
      
            - name: install amplify commands
              run: npm install -g @aws-amplify/cli
            - name: Run tests
              run: npm run test
            - name: deploy through amplify
              run: amplify publish
