name: "RUN TESTS ON PUSH then deploy"
on:
  push:
    branches:
      - main
jobs:
    test_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
           
            - name: Set up npm
              uses: actions/setup-node@v1
              with:
                node-version: '18.x'
            
            - name: Install dependencies
              run: npm install
              
            - name: install amplify commands
              run: npm install -g @aws-amplify/cli --unsage-perm=true
              
            - name: Run tests
              run: npm run test
              
            - name: PUSH steps - DEPLOYING BACKEND
              run: amplify push --yes  
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_REGION: eu-west-3

            - name: DEPLOY FRONTEND THROUGH AMPLIFY PUBLISH
              run: amplify publish
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_REGION: eu-west-3

            - name: is publiched success
              run: echo "version published successly ! :rocket:"
              


